use_frameworks!

platform :ios, '10.0'

target 'next_space_ios_arch_Example' do
  pod 'next_space_ios_arch', :path => '../'
  
  pod 'next_space_ios_arch', :path => '../'
  
  target 'next_space_ios_arch_Tests' do
    inherit! :search_paths

    
  end

end
